/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:1b64a36e-91b2-4b3d-b81b-cf70fb04a65b",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_lPCRYZF1G",
    "aws_user_pools_web_client_id": "23lnaal268ie7cbqpvvcjffmcj",
    "oauth": {}
};


export default awsmobile;
